title: Play Rock Paper Scissors Game
description: A Ruby Programmed Rock Paper Scissors Game
show_downloads: true
google_analytics: false
theme: jekyll-theme-cayman # important
repository: "bag3318/RPSG"
port: 1988
include:
  - index.md
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-cayman.gemspec
  - thumbnail.png
  - LICENSE
  - script
gems: 
  - github-pages
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
liquid:
  error_mode: warn
keep_files:
  - ".git" 
  - ".svn"
include:              
  - ".htaccess"
destination:  ./_site
layouts_dir:  _layouts
includes_dir: _includes
defaults:
  -
    values:
      layout: "default"
      author: "bag3318"
