# Setup
title:        RPSG
tagline:      Rock Paper Scissors Game
baseurl:      ""
paginate:     1
show_downloads: true

# About/contact
# author:
#   name:       Author name
#   url:        http://yourhomepage.com 

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown

# defaults:
#   # _pages
#   - scope:
#       path: "_pages/Home.txt"
#       type: pages
#     values:
#       layout: single
#       author_profile: false
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
liquid:
  error_mode: warn
keep_files:
  - ".git" 
  - ".svn"
include:              
  - ".htaccess"
destination:  ./_site
layouts_dir:  _layouts
includes_dir: _includes
defaults:
  -
    values:
      layout: "default"
      author: "bag3318"
