title: Rock Paper Scissors Game
# title_separator: "-"
# name: "RPSG"
description: A Ruby Programmed Rock Paper Scissors Game
show_downloads: true
google_analytics: false
theme: jekyll-theme-cayman # important
url: "https://bag3318.github.io/RPSG"
repository: "bag3318/RPSG"
port: 1988
include: [
  '_pages'
]
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-cayman.gemspec
  - thumbnail.png
  - LICENSE
  - script
plugins:  # gems:
  - github-pages
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
liquid:
  error_mode: warn
keep_files:
  - ".git" 
  - ".svn"
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md,txt"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
include:              
  - ".htaccess"
destination:  ./_site
layouts_dir:  _layouts
includes_dir: _includes
defaults:
  -
    values:
      layout: "default"
      author: "bag3318"

collections:
   pages:
     output: true
     permalink: /_pages/